### PR TITLE
Quick and dirty fix for #142 and #143

### LINKED ISSUE #142: Ended invasions not cleaned up
### Ended invasions should be removed from UI
---

**Summary (short):**
Invasions that have ended should always be removed from the interface.

---
**Description:**
The API returns a limited number of invasions.  If the tab goes to sleep (especially common on mobile devices) and the invasions become so old that their IDs don't show up in the API on the next update, they don't get cleaned up.

---
**If issue, Reproduction:**
Open a tab, switch to another tab for an extended period of time, and return when the API no longer has any trace of the original invasions.

---
**Mockups, screenshots, evidence:**
A new tab shows four invasions, but the old one I left up shows:

screenshot 2018-07-06 10 57 34

---

(Check one)
- [x] Issue
- [ ] Suggestion

### LINKED ISSUE #143: Ended Event Not Cleaned Up Properly
### Warframe Hub Issue
---

**Summary (short):**
Small problem with the event title removing

---
**Description:**

```
jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #event-5b3f7a6abd4f25396092b786-title"
    at Function.ga.error (jquery.min.js:2)
    at ga.tokenize (jquery.min.js:2)
    at ga.select (jquery.min.js:2)
    at Function.ga [as find] (jquery.min.js:2)
    at r.fn.init.find (jquery.min.js:2)
    at new r.fn.init (jquery.min.js:2)
    at r (jquery.min.js:2)
    at e.forEach (updaters.js?v=9e59cb353630159054a6df73651650d3d2c4385e:1)
    at Array.forEach (<anonymous>)
    at updateEvents (updaters.js?v=9e59cb353630159054a6df73651650d3d2c4385e:1)
```

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [x] Issue
- [ ] Suggestion

### PR DESCRIPTION
**Pull request by EricSihaoLin**
### Warframe Hub Pull Request
---
**Summary (short):**

This supposedly fixes #142 and #143 

---
**Description:**

Fixed #143 by removing the extra quotation mark
Fixed #142 by first adding the current update session invasion IDs into an array, and then compare ids with the entire invasionList unordered list object. If there exists an ID not in the array, then the ID is obviously expired.

---
**Fixes issue (include link):**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [x] Issue fix
- [ ] Suggestion fulfillment

### CODE REVIEW

File: assets/js/updaters.js [hunk 1]
```diff
@@ -886,6 +887,8 @@ function updateInvasions() {
     }
 
     invasions.forEach(invasion => {
+      // store current invasion ids
+      invasionIDs.push(invasion.id);
```
Comment (dsinn) [inline assets/js/updaters.js]: Given your findings on SO, I would definitely recommend switching to an object since its performance is better, at no cost of code complexity.

**Review by TobiTenno — APPROVED** [review]

**Comment by TobiTenno** [comment]
@dsinn you good with it?

**Review by dsinn — APPROVED** [review]
